# Introducing Pandas

Pandas is a Python library that makes handling tabular data easier. Since we're doing data science - this is something we'll use from time to time!
It's one of three libraries you'll encounter repeatedly in the field of data science:

In [1]:
%matplotlib inline
import numpy as np
import pandas as pd

In [2]:
# df for Data Frame

df = pd.read_csv('PastHires.csv')
df.head()

,Years Experience,Employed?,Previous employers,Level of Education,Top-tier school,Interned,Hired
0,10,Y,4,BS,N,N,Y
1,0,N,0,BS,Y,Y,Y
2,7,N,6,BS,N,N,N
3,2,Y,1,MS,Y,N,Y
4,20,N,2,PhD,Y,N,N

`head()` is a handy way to visualize what you've loaded. You can pass it an integer to see some specific number of rows at the beginning of your DataFrame:

In [3]:
# For 10 rows
df.head(10)

,Years Experience,Employed?,Previous employers,Level of Education,Top-tier school,Interned,Hired
0,10,Y,4,BS,N,N,Y
1,0,N,0,BS,Y,Y,Y
2,7,N,6,BS,N,N,N
3,2,Y,1,MS,Y,N,Y
4,20,N,2,PhD,Y,N,N
5,0,N,0,PhD,Y,Y,Y
6,5,Y,2,MS,N,Y,Y
7,3,N,1,BS,N,Y,Y
8,15,Y,5,BS,N,N,Y
9,0,N,0,BS,N,N,N

In [4]:
# For 4 rows on the tail

df.tail(4)

,Years Experience,Employed?,Previous employers,Level of Education,Top-tier school,Interned,Hired
9,0,N,0,BS,N,N,N
10,1,N,1,PhD,Y,N,N
11,4,Y,1,BS,N,Y,Y
12,0,N,0,PhD,Y,N,Y

We often talk about the "shape" of your DataFrame. 
This is just _it's_ **dimensions**.
This particular CSV file has 13 rows with 7 columns per row

In [5]:
df.shape

(13, 7)

The total size of the `data frame` is the $rows * columns$:

**e.g.** $13 \times 7$

In [6]:
df.size

91

The `len()` function gives you the number of rows in a DataFrame:

In [8]:
len(df)

13

If your DataFrame has named columns (in our case, extracted automatically from the first row of a `.csv` file,) you can get an array of them back:

In [9]:
df.columns

Index(['Years Experience', 'Employed?', 'Previous employers',
       'Level of Education', 'Top-tier school', 'Interned', 'Hired'],
      dtype='object')

Extracting a **single column** from your DataFrame looks like this - this gives you back a "Series" in Pandas:

In [11]:
df['Hired']

0     Y
1     Y
2     N
3     Y
4     N
5     Y
6     Y
7     Y
8     Y
9     N
10    N
11    Y
12    Y
Name: Hired, dtype: object

You can also extract a given `range of rows` from a named column, like so:

In [12]:
df['Hired'][:5]

# First 5 rows of `Hired`

0    Y
1    Y
2    N
3    Y
4    N
Name: Hired, dtype: object

Or even extract a single value from a specified column / row combination

To extract more than one column, you pass in an array of column names instead of a single one:

You can also extract specific ranges of rows from more than one column, in the way you'd expect:

Sorting your DataFrame by a specific column looks like this:

You can break down the number of unique values in a given column into a Series using value_counts() - this is a good way to understand the distribution of your data:

Pandas even makes it easy to plot a Series or DataFrame - just call plot():

## Exercise
Try extracting rows 5-10 of our DataFrame, preserving only the "Previous Employers" and "Hired" columns. Assign that to a new DataFrame, and create a histogram plotting the distribution of the previous employers in this subset of the data.